### PR TITLE
Move fuzzer scripts to duckdb_sqlsmith.

### PR DESCRIPTION
**Pull request by hmeriann**
Move .py scripts mentioned in the duckdb's Makefile and also move any of shell scripts.

### CODE REVIEW

**Comment by hmeriann** [comment]
@Tmonster please see the changes

**Review by Tmonster — CHANGES_REQUESTED** [review]
You don't need to add all of the fuzzer scripts. You can just add the ones directly related to fuzzing. I.e 
```
- fuzzer_helper.py
- reduce_sql.py
- run_fuzzer.py
- run_sqlancer.py
- run_sqlsmith.py
```

**Comment by Tmonster** [comment]
And then you can see if removing these files from duckdb/duckdb will fail CI

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
